### ISSUE TITLE
MudStepper - PreventStepChange async?

### ISSUE THREAD

**Issue by enkodellc** [CodeBeamOrg/CodeBeam.MudBlazor.Extensions#17]
I am looking to run an async method on the PreventStepChange and when I do it seems to lock up the whole MudStepper. The reason is that I want to save the form to the db and wait for response before moving to the next step. Any insight or suggestions?

```
        <MudStepper @ref="_stepper" ContentStyle="min-height: 400px" Linear="false" Vertical="_vertical" Color="Color.Primary" Variant="Variant.Filled" DisableAnimation="false"
                PreventStepChange="new Func<bool>(CheckChange)">

    private bool CheckChange()
    {
         if (_stepper.GetActiveIndex() == 4) {           
           return !Submit().Result;            
        }
        return false;
    }
```

**Comment by mckaragoz** [comment]
I can not say im a async expert. But did you try `async Task<bool> CheckChange()`?

**Comment by enkodellc** [comment]
Thanks, yes I tried several variations. When I do that or this the whole component freezes when I get to the step I want to run an async method in. No VS errors or JS errors, just freezes. If I get time later I will submit a PR.

```
    PreventStepChange="@(() => CheckChange().Result)">

    private async Task<bool> CheckChange()
    {
         if (_stepper.GetActiveIndex() == 4) {           
           return await Submit();            
        }
        return false;
    }
```

**Comment by mckaragoz** [comment]
If you reproduce the code with task.delay where you waiting the db, i can try something also.

**Comment by enkodellc** [comment]
Here is a test fork. If I use Wait() on my async method vs await it seems to work. Still have an issue where the StateHasChanged is not updating my MudOverlay Visible variable, in my code as well:  https://github.com/enkodellc/CodeBeam.MudExtensions/blob/dev/ComponentViewer/Pages/Components/StepperPage.razor

**Comment by PlayerModu** [comment]
@enkodellc did you end up going any further with a PR for this? I have been developing with the MudStepper component this week and these issues have been a right pain, I've only just seen they have been raised here by yourself. 

I also have the same issue around the StateHasChanged() and variables; as such I can't get any processing or progress indicators conditionally showing due to it when the data is being processed.

**Comment by mckaragoz** [comment]
> @enkodellc did you end up going any further with a PR for this? I have been developing with the MudStepper component this week and these issues have been a right pain, I've only just seen they have been raised here by yourself. 
> 
> I also have the same issue around the StateHasChanged() and variables; as such I can't get any processing or progress indicators conditionally showing due to it when the data is being processed.

Can you provide a code snippet?

**Comment by PlayerModu** [comment]
@mckaragoz yeah so using the code example provided in the docs, I have added a new component property "bool _saving" and this controls just a simple alert 

```
@if (_saving)
{
    <MudAlert Severity="Severity.Error">SAVING</MudAlert>
}
```

and then I've updated the CheckChange() method to set this to true/false after the action of that step

```
private bool CheckChange(StepChangeDirection direction)
    {
        if (_checkValidationBeforeComplete == true)
        {
            // Always allow stepping backwards, even if forms are invalid
            if (direction == StepChangeDirection.Backward)
            {
                return false;
            }
            if (_stepper.GetActiveIndex() == 0)
            {
                _saving = true;
                _form.Validate();
                _saving = false;
                return !_form.IsValid;
            }
            else if (_stepper.GetActiveIndex() == 2)
            {
                _saving = true;
                _form2.Validate();
                _saving = false;
                return !_form2.IsValid;
            }
            else
            {
                return false;
            }
        }
        else
        {
            return false;
        }
    }
```

Then running through the form via the browser, at no point does the Alert show, even when debugging and I've stopped on a line just after "_saving" has been set to true. Also adding "StateHasChanged()" after each "_saving" change value doesn't show the banner?

**Comment by enkodellc** [comment]
@PlayerModu  I copied the Mudstepper component locally and made my changes. I never submitted a PR as it was a bit more custom. I will share though I cannot promise it will work as you expect. I do use it in production.  I did this months ago and haven't synced any changes from Codebeam since Nov. 22

https://github.com/enkodellc/MudStepper/tree/main

Feel free to use it and submit a PR or not use it. Just if you do and make it better send it back with your updates :)

**Comment by mckaragoz** [comment]
@PlayerModu @enkodellc Now i understand the issue. I obsoleted the PreventStepChange and added PreventStepChangeAsync, is it what you want?


https://user-images.githubusercontent.com/78308169/228794860-f74b3c88-0a0b-4b8c-924b-ac5a6cb3488c.mp4

**Comment by PlayerModu** [comment]
@mckaragoz ah that looks great! yeah that looks to be working as expected :)

**Comment by mckaragoz** [comment]
@PlayerModu Even better, added a Loading parameter.


https://user-images.githubusercontent.com/78308169/228820724-304ce370-2051-43f1-a4e1-04579aa0b369.mp4

**Comment by PlayerModu** [comment]
@mckaragoz that looks even better :D Thank you for responding and providing a potential solution so quickly!

What would be the timeline on getting your PR for this completed and out in a new release?

**Comment by mckaragoz** [comment]
> @mckaragoz that looks even better :D Thank you for responding and providing a potential solution so quickly!
> 
> What would be the timeline on getting your PR for this completed and out in a new release?

6.4.6 just released 🙂 Please note that PreventStepChangeAsync uses `Task<bool>` instead of `bool`.

**Comment by PlayerModu** [comment]
@mckaragoz Thank you for providing a solution to the problem so quickly :) I'll reach out if I come across any more issues related to this issue
